config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :docs

  authenticated :user do 
    root 'docs#index', as: "authenticated_root"
  end
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doc.rb
class Doc < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]
  
  def index
    @docs = Doc.where(user_id: current_user).order("created_at DESC")
  end

  def create
    @doc = current_user.docs.build(doc_params)
    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def new
    @doc = current_user.docs.build
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private

    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
	= f.input :title
	= f.input :content
	= f.submit :submit, class: "button"

app/views/docs/create.html.haml
%h1 Docs#create
%p Find me in app/views/docs/create.html.haml

app/views/docs/destroy.html.haml
%h1 Docs#destroy
%p Find me in app/views/docs/destroy.html.haml

app/views/docs/edit.html.haml
.wrapper_with_padding
	%h1 Edit Doc
	= render 'form'
	= link_to 'Cancel', doc_path(@doc)

app/views/docs/index.html.haml
.wrapper_with_padding
	#docs.clearfix
		- unless @docs.blank?
			- @docs.each do |doc|
				%a{ href: (url_for [doc])}
					.doc
						%p.title= doc.title
						%p.date= time_ago_in_words(doc.created_at)  + ' ago'
						%p.content= truncate(doc.content, length: 50)
		- else
			%h2 Create Doc!
			%p start creating documents and organizing your life!
			%button= link_to "Create Doc", new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
	%h1 New Doc
	= render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
	#doc_show
		%h1.title= @doc.title
		%p= simple_format(@doc.content)
     	
		.buttons
			= link_to 'Fix Doc', edit_doc_path(@doc), class: "button"
			= link_to 'Trash It', doc_path(@doc), method: :delete, data: { confirm: 'Are you Sure?'}, class: "button"

app/views/docs/update.html.haml
%h1 Docs#update
%p Find me in app/views/docs/update.html.haml

app/views/layouts/application.html.haml
!!!
%html
%head
  %title File Cabinet | Your life's work!
  %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}
  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_importmap_tags
%body
  %header
    .header-inner
      = link_to 'File Cabinet', root_path, id: "logo"

      %nav
        - if user_signed_in?

          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete

        - else
          = link_to "Sign In", new_user_session_path

  %p.notice= notice
  %p.alert= alert
  = yield

app/views/welcome/index.html.haml
#banner
	.banner_content
		%h1 File Cabinet
		%p Your lifes work.Organised always.
		%button= link_to "Enter", new_user_registration_path
#callouts
	.callouts_inner
		.wrapper
			.callout
				%h2 organize
				%p Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
#bottom-cta
	.wrapper
		%h2 Go ahead!
		%br 
		%button= link_to "Join now", new_user_registration_path, class: "button"